import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar/Navbar";


const inter = Inter({ subsets: ["latin"] });
const mont = Montserrat({
  subsets: ["latin"],
  weight: '500'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mont.className}>
        <Navbar />
        <div className=" pt-16 w-full h-">
          {children}
        </div>
      </body>
    </html>
  );
}
